# Generated by Django 2.1.5 on 2019-02-08 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartpredict', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('date_added', models.DateTimeField(verbose_name='Date person was added')),
            ],
        ),
        migrations.DeleteModel(
            name='Person',
        ),
    ]
