# Generated by Django 2.1.5 on 2019-04-25 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartpredict', '0003_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='forex_api',
            field=models.CharField(default='api', max_length=300),
            preserve_default=False,
        ),
    ]
