# Generated by Django 2.1.5 on 2019-04-25 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smartpredict', '0004_user_forex_api'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='UserDetails',
        ),
    ]
